phonepoll/config/routes.rb
Phonepoll::Application.routes.draw do
  resources :polls

  root :to => 'polls#index'

end

phonepoll/app/models/poll.rb
class Poll < ActiveRecord::Base
  # attr_accessible :title, :body
end

phonepoll/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

phonepoll/app/controllers/polls_controller.rb
class PollsController < ApplicationController
  # GET /polls
  # GET /polls.json
  def index

    account_sid = 'AC14aa346613c89fec467663aad46c05a2'
    auth_token = '0e43d0a04e110f7faa2692e388b0c7f5'
   
    client = Twilio::REST::Client.new(account_sid, auth_token)
  end


  # def process_sms
  #   account_sid = 'AC14aa346613c89fec467663aad46c05a2'
  #   auth_token = '0e43d0a04e110f7faa2692e388b0c7f5'
   
  #   client = Twilio::REST::Client.new(account_sid, auth_token)

  #   @city = params[:FromCity].capitalize
  #   @state = params[:FromState]

  #   render 'process_sms.xml.erb', :content_type => 'text/xml'

  # end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/new
  # GET /polls/new.json
  def new
    @poll = Poll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/1/edit
  def edit
    @poll = Poll.find(params[:id])
  end

  # POST /polls
  # POST /polls.json
  def create
    account_sid = 'AC14aa346613c89fec467663aad46c05a2'
    auth_token = '0e43d0a04e110f7faa2692e388b0c7f5'
   
    client = Twilio::REST::Client.new(account_sid, auth_token)

    @city = params[:FromCity].capitalize
    @state = params[:FromState]

    render 'process_sms.xml.erb', :content_type => 'text/xml'
  end

  # PUT /polls/1
  # PUT /polls/1.json
  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end
end

phonepoll/app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

phonepoll/app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

phonepoll/app/views/polls/index.html.erb
<div class="polls">
  <div class="left">
    <h1> Yes </h1>

  </div>


  <div class="right">
    <h1> No </h1>
  </div> 
</div>

phonepoll/app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

phonepoll/app/views/polls/process_sms.xml.erb
<Response>
  <Sms>Hey, thanks for the text! Hmm... you wouldn't be from <%= @city %>, <%= @state %> by any chance?</Sms>
</Response>

phonepoll/app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>