Appointments/config/routes.rb
Appointments::Application.routes.draw do
  resources :people

  resources :teams

  match 'teams/add_to_team/:id' => "teams#add_to_team", :via => :post, :as => 'add_to_team'
  match 'teams/remove_from_team/:id' => "teams#remove_from_team", :via => :post, :as => 'remove_from_team'

  root :to => 'teams#index'

end

Appointments/app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :person_id, :team_id

  belongs_to :team
  belongs_to :person

  def find_teamate
    @self = self.id
    @teams = @self.teams
    @membership = @self.memberships
  end

end

Appointments/app/models/pairing.rb
class Pairing < ActiveRecord::Base
  attr_accessible :date, :person_id, :partner_id, :team_id

  belongs_to :persons

end

Appointments/app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :email, :name, :memberships

  has_many :memberships
  has_many :teams, :through => :memberships
  has_many :pairings
end

Appointments/app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :memberships

  has_many :memberships
  has_many :people, :through => :memberships

  def generate_pairs
    @pairs = []
    @new_pair = []
    @members = self.people.all
    @members.each do |member|

      if member.has_meeting == nil || false
        @new_pair << member

        if @new_pair.length == 2

          OneOnOne.send_pair_email(@new_pair).deliver

          # find a way to reduce the Big O here later.  
          @new_pair.each do |pairee| 
            #Switching boolean here accounts for a 'one-person pair' 
            pairee.has_meeting = true 
            
            #Creating pairing history to check against for later rounds of emailing
            if @new_pair.index(pairee) == 0
              pairee.pairings << Pairing.new(:partner_id => @new_pair[1].id, :team_id =>self.id)
            else
              pairee.pairings << Pairing.new(:partner_id => @new_pair[0].id, :team_id =>self.id)
            end
          end   
          @pairs << @new_pair
          @new_pair = []
        end
      end 
    end
  end

end

Appointments/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Appointments/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end


  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create

    if params[:person][:team_id]
      @person.teams.create(:user_id => @person.id)
      person.teams = params[:person][:team_id].to_i
    else

      @person = Person.new(params[:person])
      @person.teams.create(:user_id => @person.id)
    end

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

Appointments/app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
    @person = Person.new
    @count = Person.all.length

    respond_to do |format|
      format.html 
      format.json { render json: @teams }
    end
  end

  def make_appointments
    # @teams.schedule
  end

  def show
    @team = Team.find(params[:id])
    @members = @team.people
    # Will paginate if scaled
    @employees = Person.all
    respond_to do |format|
      format.html 
      format.json { render json: @team }
    end
  end


  def new
    @team = Team.new

    respond_to do |format|
      format.html 
      format.json { render json: @team }
    end
  end

  def add_to_team

    @team = Team.find(params[:team_id])
    @team.memberships.create(:person_id => params[:id])
    redirect_to @team
  end

  def remove_from_team
    @team = Team.find(params[:team_id])
    @membership = @team.memberships.find_by_person_id(params[:id])
    @membership.destroy 

    redirect_to @team
  end

  def edit
    @team = Team.find(params[:id])
  end


  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

Appointments/app/helpers/application_helper.rb
module ApplicationHelper
end

Appointments/app/helpers/people_helper.rb
module PeopleHelper
end

Appointments/app/helpers/teams_helper.rb
module TeamsHelper
end

Appointments/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Appointments
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body

    .wrapper
      = yield

Appointments/app/views/people/_form.html.haml
= form_for(@person) do |f|
  - if @person.errors.any?
    #error_explanation
      %h2
        = pluralize(@person.errors.count, "error")
        prohibited this person from being saved:
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .actions
    = f.submit "Add Member", :class =>"btn"

Appointments/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

Appointments/app/views/people/index.html.haml
%h1 Listing people
%table.table.table-striped.table-hover.table-bordered
  %tr
    %th Name
    %th Email
    %th
    %th
    %th
  - @people.each do |person|
    %tr
      %td= person.name
      %td= person.email
      %td= link_to 'Show', person, :class => "btn"
      %td= link_to 'Edit', edit_person_path(person), :class => "btn"
      %td= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn"
%br/
= link_to 'New Person', new_person_path, :class =>"btn"
= link_to "Manage Teams", teams_path, :class =>"btn"

Appointments/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

Appointments/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>