config/routes.rb
PartyCrashers::Application.routes.draw do

  get 'tags/:tag' , to: 'parties#index', as: :tag

  resources :parties do 
    member { post :vote }
  end
  

  resources :parties do
    member do
      post 'attend'
    end
  end

  resources :images

  devise_for :users

  resource :comments, :only => [:create, :edit]
  

  root :to => 'parties#index'

  

end

app/models/attended_party.rb
class AttendedParty < ActiveRecord::Base
  attr_accessible :party_id, :user_id

  belongs_to :party
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :party_id, :user_id

  belongs_to :party
  belongs_to :user
end

app/models/hosted_party.rb
class HostedParty < ActiveRecord::Base
  attr_accessible :party_id, :user_id

  belongs_to :party
  belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :party_id

  belongs_to :party
end

app/models/party.rb
class Party < ActiveRecord::Base

  attr_accessible :address, :date, :latitude, :longitude, :rating, :state, :time, :title, :zipcode, :description, :main_image, :tag_list
  #acts_as_taggable and :tag_list are provide by the acts-as_taggable_on gem.
  acts_as_taggable


  has_many :hosted_parties
  has_many :attended_parties
  has_many :tags, :through => :party_tag
  has_many :party_tags
  has_many :images
  has_many :comments
  has_many :users, :through => :user_parties
  has_many :user_parties

  #This through the active record reputation gem
  has_reputation :votes, source: :user, aggregated_by: :sum
  

  #This is the GA Engineer bit
  # has_many :hosts, :through => :hosted_party, :source => :user
  # has_many :attendees, :through => :attended_party, :source => :user

  geocoded_by :geolocate
  after_validation :geocode

  def geolocate
    "#{self.address}"', '"#{self.state}"', '"#{self.zipcode}"
    # binding.pry
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end


  def crashed(id,party)
    # binding.pry
    user = User.find(id)
    # binding.pry
    party = Party.find(party)
    # binding.pry
    user.parties.include?(party)
    # binding.pry
    # binding.pry
  end

end

app/models/party_tag.rb
class PartyTag < ActiveRecord::Base
  attr_accessible :party_id, :tag_id

  belongs_to :tag
  belongs_to :party
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title

  has_many :parties, :through => :party_tag
  has_many :party_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :age
  # attr_accessible :title, :body   
  #Write a unit test to check this, if not use tha
  has_many :hosted_parties
  has_many :attended_parties
  has_many :comments, :through => :parties
  has_many :parties, :through => :user_parties
  has_many :user_parties

  #has_reputation :votes, source: {reputation: :votes, of: :parties}, aggregated_by: :sum

  #This is the GA Engineer bit
  # has_many :parties_hosted, :through => :hosted_party, :source => :party
  # has_many :parties_crashed, :through => :attended_party, :source => :party

end

app/models/user_party.rb
class UserParty < ActiveRecord::Base
  attr_accessible :host, :party_id, :user_id

  belongs_to :party
  belongs_to :user

  # def attend
  # 	# self.
  # end

  # def host
  # end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new(params[:comment])
        # assigns user id to the comment 
        #@comment.user_id = current_user.id
        @comment.save!
        render @comment
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

    def create
    	# binding.pry
        @image = Image.new(params[:image])
        @image.save!
        render @image
    end

    def new
    binding.pry
    end

    def show
    	@image = Image.find(params[:id])
    end

    def destroy
      @image = Image.find(params[:id])
      @image.destroy

      respond_to do |format|
        format.html { redirect_to images_url }
        format.json { head :no_content }
      end
    end

    def index
      @images = Image.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @images }
      end
    end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]

  def index

    if params[:search] 
      @parties = Party.search(params[:search])

    elsif params[:tag]
      @parties = Party.tagged_with(params[:tag])
    else
      @parties = Party.find_with_reputation(:votes, :all, order: "votes desc")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
      format.js 
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find(params[:id])
    respond_to do |format|
      format.html# show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.json
  def create

    @party = Party.new(params[:party])

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @party = Party.find(params[:id])
    @party.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thanks for voting"
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params)
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end

  def attend
    # binding.pry
    @user_party = UserParty.new
    @user_party.party_id, @user_party.user_id = params[:id], params[:user_id]
    @user_party.save!
    render :template => 'parties/attend', :locals => { :user_party => @user_party }, :content_type => 'text/javascript'
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def title
  end
  
end

app/controllers/users_controller.rb
class UsersController < Devise::SessionsController
  def create
    super
  end
	 def update
	   #edit here
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/comments/_comment.html.erb
<!-- will render comments to the body -->
<div class="comments-part">
    <div class="email">
        Posted by <%= current_user.email %><br><br>
    </div>
    <div class ="comment-body">
        <%= comment.body %><br>
    </div>
    <div class="post-time">
        <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago <br>
    </div>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
<!-- creates new comment but defaulting id to 1 -->

    <%= form_for Comment.new(:party_id => party.id), :remote => :true do |f| %>
            <div class="fi:r:eld">
                <%= f.hidden_field :party_id %>
            </div>
            <div class="field">
                <%= f.text_area :body, :class => 'box' %>
            </div>
            <div class="field">
                <%= f.submit 'post', :class => 'button'  %>
            </div>
    <% end %>

</div>

app/views/comments/test.erb
<!-- will render comments to the body -->
<div class="comments-part">
    <%= comment.body %>
</div>

app/views/images/_form.html.erb
<div class="image-form">

    <%= form_for Image.new(:party_id => party.id), :remote => :true do |f| %>

        
            <div class="field">
                <%= f.hidden_field :party_id %>
            </div>

            <div class="field">
                <%= f.text_field :name %>
            </div>

            <div class="field">
                <%= f.submit %>
            </div>
    <% end %>

</div>

app/views/images/_image.html.erb
<div class="images-part">
    <%# @image.each do |image| %>
        <%= image_tag image.name %>
    <%# end %>
</div>

app/views/images/index.html.erb
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Nested</title>
  <link href="assets/style.css" rel="stylesheet" type="text/css" media="screen" />
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/jquery-1.7.1.min.js"><\/script>')</script>
  <script src="assets/jquery.nested.js"></script>
  <script src="assets/makeboxes.js"></script>
  </head>
  <body>

  <ul><h3> Images From All the Parties!</h1></ul>

  <% @images.each do |image| %>
  <%= render image %>
  <% end %>

<a class="btn" id="prepend">Prepend</a>

<div id="container">
  <div class="box size11">1</div>
  <div class="box size21">2</div>
  <div class="box size32">3</div>
  <div class="box size11">4</div>
  <div class="box size21">5</div>
  <div class="box size12">6</div>
  <div class="box size21">7</div>
  <div class="box size11">8</div>
  <div class="box size31">9</div>
  <div class="box size22">10</div>
  <div class="box size11">11</div>
  <div class="box size21">12</div>
  <div class="box size12">13</div>
  <div class="box size21">14</div>
  <div class="box size23">15</div>
  <div class="box size22">16</div>
  <div class="box size11">17</div>
  <div class="box size21">18</div>
  <div class="box size12">19</div>
  <div class="box size21">20</div>
  <div class="box size22">21</div>
  <div class="box size23">22</div>
  <div class="box size11">23</div>
  <div class="box size21">24</div>
  <div class="box size12">25</div>
  <div class="box size21">26</div>
  <div class="box size22">27</div>
  <div class="box size22">28</div>
</div>

<a class="btn" id="append">Append</a>

  <script type="text/javascript" >
  
  $(function() { 
   
    $('#container').nested(); 
    
    $('#prepend').click(function(){
      var boxes = makeBoxes();
      $('#container').prepend(boxes).nested('prepend',boxes);
    })
    $('#append').click(function(){
      var boxes = makeBoxes();
      $('#container').append(boxes).nested('append',boxes);     
    })

  });
  
  
</script>

</body>
</html>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PartyCrashers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header">	

		<div id="user_nav">
			<%= image_tag('logo.png') %>
			<%= link_to "Home", root_path %> | <%= link_to "Create Party", new_party_path %> | <%= link_to "Search", parties_path %> | <%= link_to "About", parties_path %> | <%= link_to "Contact", parties_path %> | 

			<% if user_signed_in? %> 

				Signed in as <%= current_user.email %>.  Not you? | <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

			<% else %>

				<%= link_to "Sign up", new_user_registration_path, :id => "sign-up" %> or <%= link_to "Sign in", parties_path, :id => "sign-in", :remote => true %>


			<% end %> |


				<%= form_tag parties_path, :id => "search-box", :method => :get do %>

					    <%= text_field_tag :search, params[:search] %>
					    <%= submit_tag "Search", :name => nil %>

				<% end %>

		  </div>

		</div>

			<div id="deviseflash">
				<p class="notice"><%= notice %></p>
	      	<p class="alert"><%= alert %></p>
	    </div>

		</div>
	</div>
  </div>


  <div id="content">
		<%= yield %>
	</div>

	<div id="footer">
		Copyright © 2013 Pry or Die. All rights reserved.
	</div>

</body>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :main_image %><br />
    <%= f.text_field :main_image %>
  </div>

  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (seperated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/attend.js.erb
$(document).ready(function() {
	$('button_to').click(function(){
		$(this).fadeOut('slow')
	});
});

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6ZYTVUPqC5THPhI-QaiTF4YMl2fQfOYs&sensor=false">
</script>

<script type="text/javascript">

    $(function() {
          initialize();


      <% Party.all.each do |p| %>
         partyMarker(<%= p.latitude ? p.latitude : 0 %>, <%= p.longitude ? p.longitude : 0 %>, "<%= p.title %>");
      <% end %>
  });

</script>

<div class="left-column">

  <ul><h3> Parties near You</h1></ul>



  <% @parties.each do |party| %>


      <div id="party-id-<%= party.id %>">

        <% if user_signed_in? %>
        <h4 class="party-title"><%= link_to party.title, new_user_registration_path %></h4>


          <div class="party-info">

          <td><%= link_to image_tag( party.main_image), party %></td>
          <% if party.crashed(current_user.id, party.id) == false %>
          

            <td id="crash"><%= button_to "Crash Party!", { :action => "attend", :id => party.id, :user_id => current_user.id },
                    :confirm => "See You There!", :method => :attend,:remote => :true %></td>
          <% else %>

           <td></td>

          <% end %>
          <%= party.address %>
          <%= party.date.strftime("%A, %B %e"    ) %> 
          <%= pluralize party.reputation_for(:votes).to_i, "vote" %>
          <%= raw party.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %> 
          <%= link_to image_tag('thumbsup.png', :alt => "thumbsup", :class => "thumb"), vote_party_path(party, type: "up"), method: "post" %> <%= link_to image_tag('thumbsdown.png', :alt => "thumbsdown", :class => "thumb"), vote_party_path(party, type: "down"), method: "post" %>                      

        <% else %>

        <% end %> 
          </div>
      </div>

  <% end %>
  <%= link_to 'New Party', new_party_path %>
</div>

<div class="right-column">

  <div id="map-canvas">
  </div>

</div>

<div class="sidebar">
  <div id="tag_cloud">
  <% tag_cloud Party.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

</div>

app/views/parties/index.js.erb
if 
	($("#sign-in").find("#toggle-login").length) {
	 $("#toggle-login").remove();
}
else {
	$('#sign-in').append("<%= j(render :partial => 'devise/sessions/new') %>");
	$('#sign-in').find("#toggle-login").slideToggle();
}

app/views/parties/new.html.erb
<h1>Wheres the party at?</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<div class="left-column">
    <div class ="party-title">
	   <%= @party.title %>  
    </div>
    <h2>Address: <%=@party.address%></h2>
	<h3>Date: <%= @party.date.to_s(:date) %></h3>
	<h3> <%= pluralize @party.reputation_for(:votes).to_i, "vote" %></h3>
	 <%= image_tag @party.main_image %>

	 <h3> Description </h3>
	<p> <%=@party.description %></p>

</div>

<!-- JOAQUIN, MOVE TO 3 COLUMN FORMAT FOR COMMENTING? -->



<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>

<div class ="comments"> 
<h2>Comments</h2>
    <% @party.comments.each do |comment| %>
        <%= render comment %>
    <% end %>
</div>
<div class="right-column">
        <%= render :partial => 'comments/form', :locals => {:party => @party} %>
</div>

    <%= render :partial => 'images/form', :locals => {:party => @party} %>


<div class ="images">
    <% @party.images.each do |image| %>
        <%= render image %>
    <% end %>
</div>

app/views/tags/title_string.html.erb
<h1>Tags#title:string</h1>
<p>Find me in app/views/tags/title:string.html.erb</p>